project:
  type: website

website:
  title: "James Horine"
  navbar:
    left:
      - text: "**Research**"
        href: Research.qmd
      - text: "**CV**"
        href: media/_cv.pdf
      - text: "**Teaching**"
        href: Teaching.qmd
        
    tools:
        - icon: github
          href: https://github.com/jameshorine
          test: James' GitHub
execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

output-dir: _site

