---
title: ""
---

# Conference Presentations

-   [osQF](https://www.osqf.org/) 2025: [Tidyagronomy](https://docs.google.com/presentation/d/1u3HbP-FiQe6QhLHCFn73zlCKUTz2Yk56GsjjJxOb3P8/edit?usp=sharing) - An R package to Quantify Growing Degree Units (and Impacts on Agricultural Commodity Markets)

# Research Projects and Collaborations

-   Python implementation of `bolasso`: (in progress, 12/2024) Combining aspects of `fastFeatures`, `bolasso`, and research from several authors to build a robust bootstrap lasso package for the modern data science and statistical environment.
    -   Collaborators:
        -   [Daniel Molitor](https://www.dmolitor.com/){target="_blank"}
        -   [Daniel Eubanks](https://www.linkedin.com/in/james-daniel-eubanks/){target="_blank"}
-   [fastFeatures](https://github.com/jameshorine/fastFeatures) is an `R` package built from the ground up with one goal in mind: High-speed variable selection in typical statistical/data science settings so that you may (and shall) build a predictive model that is easy to explain and share.
    -   Collaborators:
        -   [Carson Sprock](https://www.linkedin.com/in/carson-sprock-68571732/)
-   [TidyAgronomy](https://github.com/modern-agronomy/tidyagronomy) is the first “tidyverse” `R` Package to unify the data and model framework of commonly used features for agronomic data science at scale.
    -   Collaborators:
        -   [Lucky Mehra](https://www.researchgate.net/profile/Lucky-Mehra)
        -   [Paul Tanger](https://www.linkedin.com/in/paultanger/)
        -   [Mohammad Bannayan](https://scholar.google.com/citations?user=IVd2mBUAAAAJ&hl=en)

# Patents

-   [**US020240119542A120240411**](https://patentimages.storage.googleapis.com/1b/af/2e/60fd122f1f4990/US20240119542A1.pdf){target="_blank"}: Systems and Methods for Assessing Crop-Damaging Factors Associated with Agronomic Fields.

# Research Interests

-   Time Series, Frequency and Spectral Estimation

-   Machine Learning Approximations to Auto-Regressive Time Series Model Problems. Quantile Auto-Regression and QAR-Forests.

-   Dimensionality Reduction

-   High-Speed & Approx. Correct Model Solutions, Capabilities, and Pipelines.

-   Engineered Systems and Machine Learning System Architecture

-   Crop, Pest, and Disease Modeling for Commercial Agricultural Applications.
